import { Event } from '../event'

const evnets = [
  'API:UPDATECOPYBOARDLIST',
  'API:GETCOPYBOARD',
  'API:POSTCOPYBOARD',
  'API:DELETECOPYBOARD',
  'API:UPDATECOPYBOARD',
  'API:SYNCCOPYBOARD',
]
